version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
    networks:
      - my-network

  content:
    image: content-calendar:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge